// Auto-generated by Phase A script
const BLEACHING_DATA = {
  "metadata": {
    "generated": "2026-02-04T16:14:31.408583",
    "source": "Moni1000 2020-2024 (v3)",
    "n_sites": 26,
    "n_years": 5,
    "annual_summary_method": "all-spot mean (N=2288 observations)",
    "heatmap_method": "site-level mean (26 sites × 5 years)"
  },
  "annual_summary": [
    {
      "year": 2020,
      "mean_bleaching": 17.0,
      "mean_mortality": 0.9
    },
    {
      "year": 2021,
      "mean_bleaching": 16.8,
      "mean_mortality": 0.6
    },
    {
      "year": 2022,
      "mean_bleaching": 37.6,
      "mean_mortality": 15.2
    },
    {
      "year": 2023,
      "mean_bleaching": 12.3,
      "mean_mortality": 0.2
    },
    {
      "year": 2024,
      "mean_bleaching": 48.4,
      "mean_mortality": 18.7
    }
  ],
  "sites": [
    {
      "site_no": 16,
      "name": "黒島～新城島",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.3,
      "lon": 124.0,
      "name_en": "黒島～新城島"
    },
    {
      "site_no": 15,
      "name": "シモビシ～仲間崎沖",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.3,
      "lon": 124.0,
      "name_en": "シモビシ～仲間崎沖"
    },
    {
      "site_no": 14,
      "name": "カタグァー周辺",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.3,
      "lon": 124.1,
      "name_en": "カタグァー周辺"
    },
    {
      "site_no": 13,
      "name": "小浜島周辺",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.3,
      "lon": 124.0,
      "name_en": "小浜島周辺"
    },
    {
      "site_no": 11,
      "name": "平久保崎～宮良湾",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.3,
      "lon": 124.2,
      "name_en": "平久保崎～宮良湾"
    },
    {
      "site_no": 17,
      "name": "崎山湾（西表島西部）周辺",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.4,
      "lon": 123.9,
      "name_en": "崎山湾（西表島西部）周辺"
    },
    {
      "site_no": 12,
      "name": "川平～大崎",
      "region": "八重山",
      "region_en": "Yaeyama",
      "lat": 24.6,
      "lon": 124.3,
      "name_en": "川平～大崎"
    },
    {
      "site_no": 25,
      "name": "多良間島周辺",
      "region": "宮古",
      "region_en": "Miyako",
      "lat": 24.6,
      "lon": 124.7,
      "name_en": "多良間島周辺"
    },
    {
      "site_no": 9,
      "name": "宮古島周辺",
      "region": "宮古",
      "region_en": "Miyako",
      "lat": 24.9,
      "lon": 125.2,
      "name_en": "宮古島周辺"
    },
    {
      "site_no": 10,
      "name": "八重干瀬",
      "region": "宮古",
      "region_en": "Miyako",
      "lat": 25.0,
      "lon": 125.2,
      "name_en": "八重干瀬"
    },
    {
      "site_no": 8,
      "name": "大東諸島",
      "region": "沖縄本島",
      "region_en": "Okinawa Main Island",
      "lat": 25.9,
      "lon": 131.2,
      "name_en": "大東諸島"
    },
    {
      "site_no": 4,
      "name": "東村～奥",
      "region": "沖縄本島",
      "region_en": "Okinawa Main Island",
      "lat": 26.1,
      "lon": 127.7,
      "name_en": "東村～奥"
    },
    {
      "site_no": 5,
      "name": "恩納村～残波岬",
      "region": "沖縄本島",
      "region_en": "Okinawa Main Island",
      "lat": 26.1,
      "lon": 127.6,
      "name_en": "恩納村～残波岬"
    },
    {
      "site_no": 7,
      "name": "慶良間諸島中心海域（阿嘉島、座間味、渡嘉敷周辺）",
      "region": "沖縄本島",
      "region_en": "Okinawa Main Island",
      "lat": 26.2,
      "lon": 127.3,
      "name_en": "慶良間諸島中心海域（阿嘉島、座間味、渡嘉敷周辺）"
    },
    {
      "site_no": 6,
      "name": "水納島・伊是名島・伊平屋島",
      "region": "沖縄本島",
      "region_en": "Okinawa Main Island",
      "lat": 26.6,
      "lon": 127.8,
      "name_en": "水納島・伊是名島・伊平屋島"
    },
    {
      "site_no": 18,
      "name": "父島周辺",
      "region": "小笠原",
      "region_en": "Ogasawara",
      "lat": 27.1,
      "lon": 142.2,
      "name_en": "父島周辺"
    },
    {
      "site_no": 3,
      "name": "奄美大島",
      "region": "鹿児島離島",
      "region_en": "Kagoshima Islands",
      "lat": 28.5,
      "lon": 129.6,
      "name_en": "奄美大島"
    },
    {
      "site_no": 2,
      "name": "小宝島周辺",
      "region": "鹿児島離島",
      "region_en": "Kagoshima Islands",
      "lat": 29.2,
      "lon": 129.2,
      "name_en": "小宝島周辺"
    },
    {
      "site_no": 1,
      "name": "屋久島・種子島周辺",
      "region": "鹿児島本土",
      "region_en": "Kagoshima Mainland",
      "lat": 30.4,
      "lon": 130.5,
      "name_en": "屋久島・種子島周辺"
    },
    {
      "site_no": 23,
      "name": "鹿児島県南部沿岸",
      "region": "鹿児島本土",
      "region_en": "Kagoshima Mainland",
      "lat": 31.6,
      "lon": 130.7,
      "name_en": "鹿児島県南部沿岸"
    },
    {
      "site_no": 24,
      "name": "天草周辺",
      "region": "九州・四国",
      "region_en": "Kyushu/Shikoku",
      "lat": 32.5,
      "lon": 130.0,
      "name_en": "天草周辺"
    },
    {
      "site_no": 20,
      "name": "壱岐・対馬・五島列島",
      "region": "九州・四国",
      "region_en": "Kyushu/Shikoku",
      "lat": 32.6,
      "lon": 128.6,
      "name_en": "壱岐・対馬・五島列島"
    },
    {
      "site_no": 22,
      "name": "四国南西岸(宇和海～足摺岬)",
      "region": "九州・四国",
      "region_en": "Kyushu/Shikoku",
      "lat": 33.0,
      "lon": 132.5,
      "name_en": "四国南西岸(宇和海～足摺岬)"
    },
    {
      "site_no": 21,
      "name": "串本周辺",
      "region": "九州・四国",
      "region_en": "Kyushu/Shikoku",
      "lat": 33.5,
      "lon": 135.8,
      "name_en": "串本周辺"
    },
    {
      "site_no": 26,
      "name": "田辺周辺",
      "region": "本州",
      "region_en": "Honshu",
      "lat": 33.7,
      "lon": 135.4,
      "name_en": "田辺周辺"
    },
    {
      "site_no": 19,
      "name": "館山湾",
      "region": "本州",
      "region_en": "Honshu",
      "lat": 35.0,
      "lon": 139.8,
      "name_en": "館山湾"
    }
  ],
  "heatmap": {
    "bleaching": {
      "1": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 13.1,
        "2023": 0.0,
        "2024": 56.4
      },
      "2": {
        "2022": 43.8
      },
      "3": {
        "2020": 8.7,
        "2021": 5.3,
        "2022": 41.3,
        "2023": 1.3,
        "2024": 62.3
      },
      "4": {
        "2020": 2.0,
        "2021": 0.1,
        "2022": 5.3,
        "2023": 0.1,
        "2024": 57.6
      },
      "5": {
        "2020": 2.2,
        "2021": 0.1,
        "2022": 3.4,
        "2023": 0.0,
        "2024": 77.8
      },
      "6": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.3,
        "2023": 0.0,
        "2024": 88.6
      },
      "7": {
        "2020": 0.6,
        "2021": 0.2,
        "2022": 0.4,
        "2023": 0.2,
        "2024": 22.9
      },
      "8": {
        "2022": 3.8
      },
      "9": {
        "2020": 1.9,
        "2021": 0.0,
        "2022": 22.8,
        "2023": 0.0,
        "2024": 51.2
      },
      "10": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 6.9,
        "2023": 0.0,
        "2024": 67.5
      },
      "11": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 38.0,
        "2023": 0.0,
        "2024": 7.0
      },
      "12": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 58.3,
        "2023": 0.0,
        "2024": 4.9
      },
      "13": {
        "2020": 28.5,
        "2021": 47.0,
        "2022": 86.8,
        "2023": 30.7,
        "2024": 82.9
      },
      "14": {
        "2020": 59.1,
        "2021": 58.9,
        "2022": 89.5,
        "2023": 48.6,
        "2024": 94.5
      },
      "15": {
        "2020": 57.6,
        "2021": 66.0,
        "2022": 87.1,
        "2023": 50.5,
        "2024": 85.5
      },
      "16": {
        "2020": 69.5,
        "2021": 69.2,
        "2022": 90.8,
        "2023": 46.6,
        "2024": 94.1
      },
      "17": {
        "2020": 46.9,
        "2021": 44.7,
        "2022": 92.9,
        "2023": 35.7,
        "2024": 88.3
      },
      "18": {
        "2020": 14.2,
        "2021": 0.7,
        "2022": 0.5,
        "2023": 0.6,
        "2024": 0.5
      },
      "19": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.0,
        "2023": 0.0,
        "2024": 0.0
      },
      "20": {
        "2022": 2.4,
        "2023": 2.5,
        "2024": 32.7
      },
      "21": {
        "2020": 5.9,
        "2021": 0.2,
        "2022": 2.2,
        "2023": 0.3,
        "2024": 13.1
      },
      "22": {
        "2020": 3.7,
        "2021": 0.5,
        "2022": 7.4,
        "2023": 2.0,
        "2024": 32.5
      },
      "23": {
        "2020": 0.4,
        "2021": 0.9,
        "2022": 44.7,
        "2023": 7.2,
        "2024": 8.9
      },
      "24": {
        "2020": 3.3,
        "2021": 2.7,
        "2022": 3.0,
        "2023": 2.8,
        "2024": 6.3
      },
      "25": {
        "2024": 36.1
      },
      "26": {
        "2021": 0.0,
        "2022": 7.9
      }
    },
    "mortality": {
      "1": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 8.1,
        "2023": 0.0,
        "2024": 30.8
      },
      "2": {
        "2022": 1.8
      },
      "3": {
        "2020": 0.0,
        "2021": 5.3,
        "2022": 2.2,
        "2023": 0.7,
        "2024": 54.3
      },
      "4": {
        "2020": 0.1,
        "2021": 0.0,
        "2022": 5.1,
        "2023": 0.1,
        "2024": 22.8
      },
      "5": {
        "2020": 0.3,
        "2021": 0.0,
        "2022": 4.6,
        "2023": 0.0,
        "2024": 29.3
      },
      "6": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.4,
        "2023": 0.0,
        "2024": 14.3
      },
      "7": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.0,
        "2023": 0.0,
        "2024": 13.3
      },
      "8": {
        "2022": 0.1
      },
      "9": {
        "2020": 0.1,
        "2021": 0.0,
        "2022": 21.0,
        "2023": 0.0,
        "2024": 48.8
      },
      "10": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 6.9,
        "2023": 0.0,
        "2024": 67.5
      },
      "11": {
        "2020": 0.1,
        "2021": 0.0,
        "2022": 14.5,
        "2023": 0.0,
        "2024": 0.7
      },
      "12": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 55.2,
        "2023": 0.0,
        "2024": 2.5
      },
      "13": {
        "2020": 1.4,
        "2021": 1.2,
        "2022": 25.1,
        "2023": 0.1,
        "2024": 23.1
      },
      "14": {
        "2020": 1.3,
        "2021": 1.1,
        "2022": 23.8,
        "2023": 0.1,
        "2024": 41.5
      },
      "15": {
        "2020": 1.3,
        "2021": 1.8,
        "2022": 25.3,
        "2023": 0.1,
        "2024": 29.8
      },
      "16": {
        "2020": 2.8,
        "2021": 1.9,
        "2022": 20.9,
        "2023": 0.2,
        "2024": 34.8
      },
      "17": {
        "2020": 5.2,
        "2021": 1.0,
        "2022": 40.7,
        "2023": 0.4,
        "2024": 26.8
      },
      "18": {
        "2020": 3.4,
        "2021": 0.6,
        "2022": 0.4,
        "2023": 0.3,
        "2024": 0.3
      },
      "19": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.0,
        "2023": 0.0,
        "2024": 0.0
      },
      "20": {
        "2022": 1.2,
        "2023": 1.4,
        "2024": 0.7
      },
      "21": {
        "2020": 0.9,
        "2021": 0.0,
        "2022": 0.8,
        "2023": 0.1,
        "2024": 0.1
      },
      "22": {
        "2020": 0.5,
        "2021": 0.0,
        "2022": 0.6,
        "2023": 0.1,
        "2024": 5.3
      },
      "23": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 24.9,
        "2023": 2.0,
        "2024": 6.4
      },
      "24": {
        "2020": 0.0,
        "2021": 0.0,
        "2022": 0.0,
        "2023": 0.0,
        "2024": 4.0
      },
      "25": {
        "2024": 13.9
      },
      "26": {
        "2021": 0.0,
        "2022": 0.7
      }
    }
  },
  "zscore_2024": [
    {
      "site_no": 1,
      "site_name": "屋久島・種子島周辺",
      "region": "鹿児島本土",
      "z_score": 8.1,
      "bleaching_2024": 56.4,
      "mean_baseline": 3.3
    },
    {
      "site_no": 3,
      "site_name": "奄美大島",
      "region": "鹿児島離島",
      "z_score": 2.6,
      "bleaching_2024": 62.3,
      "mean_baseline": 14.2
    },
    {
      "site_no": 4,
      "site_name": "東村～奥",
      "region": "沖縄本島",
      "z_score": 23.0,
      "bleaching_2024": 57.6,
      "mean_baseline": 1.9
    },
    {
      "site_no": 5,
      "site_name": "恩納村～残波岬",
      "region": "沖縄本島",
      "z_score": 45.9,
      "bleaching_2024": 77.8,
      "mean_baseline": 1.4
    },
    {
      "site_no": 6,
      "site_name": "水納島・伊是名島・伊平屋島",
      "region": "沖縄本島",
      "z_score": 530.9,
      "bleaching_2024": 88.6,
      "mean_baseline": 0.1
    },
    {
      "site_no": 7,
      "site_name": "慶良間諸島中心海域（阿嘉島、座間味、渡嘉敷周辺）",
      "region": "沖縄本島",
      "z_score": 113.1,
      "bleaching_2024": 22.9,
      "mean_baseline": 0.4
    },
    {
      "site_no": 9,
      "site_name": "宮古島周辺",
      "region": "宮古",
      "z_score": 4.1,
      "bleaching_2024": 51.2,
      "mean_baseline": 6.2
    },
    {
      "site_no": 10,
      "site_name": "八重干瀬",
      "region": "宮古",
      "z_score": 19.1,
      "bleaching_2024": 67.5,
      "mean_baseline": 1.7
    },
    {
      "site_no": 11,
      "site_name": "平久保崎～宮良湾",
      "region": "八重山",
      "z_score": -0.1,
      "bleaching_2024": 7.0,
      "mean_baseline": 9.5
    },
    {
      "site_no": 12,
      "site_name": "川平～大崎",
      "region": "八重山",
      "z_score": -0.3,
      "bleaching_2024": 4.9,
      "mean_baseline": 14.6
    },
    {
      "site_no": 13,
      "site_name": "小浜島周辺",
      "region": "八重山",
      "z_score": 1.3,
      "bleaching_2024": 82.9,
      "mean_baseline": 48.2
    },
    {
      "site_no": 14,
      "site_name": "カタグァー周辺",
      "region": "八重山",
      "z_score": 1.7,
      "bleaching_2024": 94.5,
      "mean_baseline": 64.0
    },
    {
      "site_no": 15,
      "site_name": "シモビシ～仲間崎沖",
      "region": "八重山",
      "z_score": 1.3,
      "bleaching_2024": 85.5,
      "mean_baseline": 65.3
    },
    {
      "site_no": 16,
      "site_name": "黒島～新城島",
      "region": "八重山",
      "z_score": 1.4,
      "bleaching_2024": 94.1,
      "mean_baseline": 69.1
    },
    {
      "site_no": 17,
      "site_name": "崎山湾（西表島西部）周辺",
      "region": "八重山",
      "z_score": 1.3,
      "bleaching_2024": 88.3,
      "mean_baseline": 55.0
    },
    {
      "site_no": 18,
      "site_name": "父島周辺",
      "region": "小笠原",
      "z_score": -0.5,
      "bleaching_2024": 0.5,
      "mean_baseline": 4.0
    },
    {
      "site_no": 19,
      "site_name": "館山湾",
      "region": "本州",
      "z_score": NaN,
      "bleaching_2024": 0.0,
      "mean_baseline": 0.0
    },
    {
      "site_no": 20,
      "site_name": "壱岐・対馬・五島列島",
      "region": "九州・四国",
      "z_score": 406.2,
      "bleaching_2024": 32.7,
      "mean_baseline": 2.4
    },
    {
      "site_no": 21,
      "site_name": "串本周辺",
      "region": "九州・四国",
      "z_score": 4.1,
      "bleaching_2024": 13.1,
      "mean_baseline": 2.2
    },
    {
      "site_no": 22,
      "site_name": "四国南西岸(宇和海～足摺岬)",
      "region": "九州・四国",
      "z_score": 9.7,
      "bleaching_2024": 32.5,
      "mean_baseline": 3.4
    },
    {
      "site_no": 23,
      "site_name": "鹿児島県南部沿岸",
      "region": "鹿児島本土",
      "z_score": -0.2,
      "bleaching_2024": 8.9,
      "mean_baseline": 13.3
    },
    {
      "site_no": 24,
      "site_name": "天草周辺",
      "region": "九州・四国",
      "z_score": 11.9,
      "bleaching_2024": 6.3,
      "mean_baseline": 3.0
    }
  ],
  "cover_bleaching": {
    "data": [
      {
        "site_no": 1,
        "year": 2021,
        "cover": 40.6,
        "bleaching": 0.0
      },
      {
        "site_no": 1,
        "year": 2022,
        "cover": 36.4,
        "bleaching": 13.1
      },
      {
        "site_no": 1,
        "year": 2023,
        "cover": 39.2,
        "bleaching": 0.0
      },
      {
        "site_no": 1,
        "year": 2024,
        "cover": 32.5,
        "bleaching": 56.4
      },
      {
        "site_no": 2,
        "year": 2022,
        "cover": 50.0,
        "bleaching": 43.8
      },
      {
        "site_no": 3,
        "year": 2020,
        "cover": 37.2,
        "bleaching": 8.7
      },
      {
        "site_no": 3,
        "year": 2021,
        "cover": 41.2,
        "bleaching": 5.3
      },
      {
        "site_no": 3,
        "year": 2022,
        "cover": 43.2,
        "bleaching": 41.3
      },
      {
        "site_no": 3,
        "year": 2023,
        "cover": 42.5,
        "bleaching": 1.3
      },
      {
        "site_no": 3,
        "year": 2024,
        "cover": 17.8,
        "bleaching": 62.3
      },
      {
        "site_no": 4,
        "year": 2020,
        "cover": 32.4,
        "bleaching": 2.0
      },
      {
        "site_no": 4,
        "year": 2021,
        "cover": 40.0,
        "bleaching": 0.1
      },
      {
        "site_no": 4,
        "year": 2022,
        "cover": 35.8,
        "bleaching": 5.3
      },
      {
        "site_no": 4,
        "year": 2023,
        "cover": 38.1,
        "bleaching": 0.1
      },
      {
        "site_no": 4,
        "year": 2024,
        "cover": 34.9,
        "bleaching": 57.6
      },
      {
        "site_no": 5,
        "year": 2020,
        "cover": 41.6,
        "bleaching": 2.2
      },
      {
        "site_no": 5,
        "year": 2021,
        "cover": 51.1,
        "bleaching": 0.1
      },
      {
        "site_no": 5,
        "year": 2022,
        "cover": 54.0,
        "bleaching": 3.4
      },
      {
        "site_no": 5,
        "year": 2023,
        "cover": 49.5,
        "bleaching": 0.0
      },
      {
        "site_no": 5,
        "year": 2024,
        "cover": 39.8,
        "bleaching": 77.8
      },
      {
        "site_no": 6,
        "year": 2020,
        "cover": 62.0,
        "bleaching": 0.0
      },
      {
        "site_no": 6,
        "year": 2021,
        "cover": 63.3,
        "bleaching": 0.0
      },
      {
        "site_no": 6,
        "year": 2022,
        "cover": 73.3,
        "bleaching": 0.3
      },
      {
        "site_no": 6,
        "year": 2023,
        "cover": 65.0,
        "bleaching": 0.0
      },
      {
        "site_no": 6,
        "year": 2024,
        "cover": 65.7,
        "bleaching": 88.6
      },
      {
        "site_no": 7,
        "year": 2020,
        "cover": 30.0,
        "bleaching": 0.6
      },
      {
        "site_no": 7,
        "year": 2021,
        "cover": 35.8,
        "bleaching": 0.2
      },
      {
        "site_no": 7,
        "year": 2022,
        "cover": 29.2,
        "bleaching": 0.4
      },
      {
        "site_no": 7,
        "year": 2023,
        "cover": 30.0,
        "bleaching": 0.2
      },
      {
        "site_no": 7,
        "year": 2024,
        "cover": 23.3,
        "bleaching": 22.9
      },
      {
        "site_no": 8,
        "year": 2022,
        "cover": 7.7,
        "bleaching": 3.8
      },
      {
        "site_no": 9,
        "year": 2020,
        "cover": 22.0,
        "bleaching": 1.8
      },
      {
        "site_no": 9,
        "year": 2021,
        "cover": 32.5,
        "bleaching": 0.0
      },
      {
        "site_no": 9,
        "year": 2022,
        "cover": 28.5,
        "bleaching": 22.8
      },
      {
        "site_no": 9,
        "year": 2023,
        "cover": 34.2,
        "bleaching": 0.0
      },
      {
        "site_no": 9,
        "year": 2024,
        "cover": 19.2,
        "bleaching": 51.2
      },
      {
        "site_no": 10,
        "year": 2020,
        "cover": 11.2,
        "bleaching": 0.0
      },
      {
        "site_no": 10,
        "year": 2021,
        "cover": 22.5,
        "bleaching": 0.0
      },
      {
        "site_no": 10,
        "year": 2022,
        "cover": 25.0,
        "bleaching": 6.9
      },
      {
        "site_no": 10,
        "year": 2023,
        "cover": 27.5,
        "bleaching": 0.0
      },
      {
        "site_no": 10,
        "year": 2024,
        "cover": 13.1,
        "bleaching": 67.5
      },
      {
        "site_no": 11,
        "year": 2020,
        "cover": 25.3,
        "bleaching": 0.0
      },
      {
        "site_no": 11,
        "year": 2021,
        "cover": 30.6,
        "bleaching": 0.0
      },
      {
        "site_no": 11,
        "year": 2022,
        "cover": 27.6,
        "bleaching": 38.0
      },
      {
        "site_no": 11,
        "year": 2023,
        "cover": 25.9,
        "bleaching": 0.0
      },
      {
        "site_no": 11,
        "year": 2024,
        "cover": 25.6,
        "bleaching": 7.0
      },
      {
        "site_no": 12,
        "year": 2020,
        "cover": 21.6,
        "bleaching": 0.0
      },
      {
        "site_no": 12,
        "year": 2021,
        "cover": 35.8,
        "bleaching": 0.0
      },
      {
        "site_no": 12,
        "year": 2022,
        "cover": 12.3,
        "bleaching": 58.3
      },
      {
        "site_no": 12,
        "year": 2023,
        "cover": 15.6,
        "bleaching": 0.0
      },
      {
        "site_no": 12,
        "year": 2024,
        "cover": 22.0,
        "bleaching": 4.9
      },
      {
        "site_no": 13,
        "year": 2020,
        "cover": 29.8,
        "bleaching": 28.5
      },
      {
        "site_no": 13,
        "year": 2021,
        "cover": 36.9,
        "bleaching": 47.0
      },
      {
        "site_no": 13,
        "year": 2022,
        "cover": 29.4,
        "bleaching": 86.8
      },
      {
        "site_no": 13,
        "year": 2023,
        "cover": 30.5,
        "bleaching": 30.7
      },
      {
        "site_no": 13,
        "year": 2024,
        "cover": 30.3,
        "bleaching": 82.9
      },
      {
        "site_no": 14,
        "year": 2020,
        "cover": 7.2,
        "bleaching": 59.1
      },
      {
        "site_no": 14,
        "year": 2021,
        "cover": 10.2,
        "bleaching": 58.9
      },
      {
        "site_no": 14,
        "year": 2022,
        "cover": 9.2,
        "bleaching": 89.5
      },
      {
        "site_no": 14,
        "year": 2023,
        "cover": 11.0,
        "bleaching": 48.6
      },
      {
        "site_no": 14,
        "year": 2024,
        "cover": 6.5,
        "bleaching": 94.5
      },
      {
        "site_no": 15,
        "year": 2020,
        "cover": 23.6,
        "bleaching": 57.6
      },
      {
        "site_no": 15,
        "year": 2021,
        "cover": 27.6,
        "bleaching": 66.0
      },
      {
        "site_no": 15,
        "year": 2022,
        "cover": 21.0,
        "bleaching": 87.1
      },
      {
        "site_no": 15,
        "year": 2023,
        "cover": 22.4,
        "bleaching": 50.5
      },
      {
        "site_no": 15,
        "year": 2024,
        "cover": 16.4,
        "bleaching": 85.5
      },
      {
        "site_no": 16,
        "year": 2020,
        "cover": 15.8,
        "bleaching": 69.5
      },
      {
        "site_no": 16,
        "year": 2021,
        "cover": 19.0,
        "bleaching": 69.2
      },
      {
        "site_no": 16,
        "year": 2022,
        "cover": 17.3,
        "bleaching": 90.8
      },
      {
        "site_no": 16,
        "year": 2023,
        "cover": 18.9,
        "bleaching": 46.6
      },
      {
        "site_no": 16,
        "year": 2024,
        "cover": 15.5,
        "bleaching": 94.1
      },
      {
        "site_no": 17,
        "year": 2020,
        "cover": 36.2,
        "bleaching": 46.9
      },
      {
        "site_no": 17,
        "year": 2021,
        "cover": 47.1,
        "bleaching": 44.7
      },
      {
        "site_no": 17,
        "year": 2022,
        "cover": 27.5,
        "bleaching": 92.9
      },
      {
        "site_no": 17,
        "year": 2023,
        "cover": 28.2,
        "bleaching": 35.7
      },
      {
        "site_no": 17,
        "year": 2024,
        "cover": 22.1,
        "bleaching": 88.3
      },
      {
        "site_no": 18,
        "year": 2020,
        "cover": 43.3,
        "bleaching": 14.2
      },
      {
        "site_no": 18,
        "year": 2021,
        "cover": 48.3,
        "bleaching": 0.7
      },
      {
        "site_no": 18,
        "year": 2022,
        "cover": 50.8,
        "bleaching": 0.5
      },
      {
        "site_no": 18,
        "year": 2023,
        "cover": 50.0,
        "bleaching": 0.6
      },
      {
        "site_no": 18,
        "year": 2024,
        "cover": 52.5,
        "bleaching": 0.5
      },
      {
        "site_no": 19,
        "year": 2020,
        "cover": 3.8,
        "bleaching": 0.0
      },
      {
        "site_no": 19,
        "year": 2021,
        "cover": 3.8,
        "bleaching": 0.0
      },
      {
        "site_no": 19,
        "year": 2022,
        "cover": 3.8,
        "bleaching": 0.0
      },
      {
        "site_no": 19,
        "year": 2023,
        "cover": 2.5,
        "bleaching": 0.0
      },
      {
        "site_no": 19,
        "year": 2024,
        "cover": 2.5,
        "bleaching": 0.0
      },
      {
        "site_no": 20,
        "year": 2022,
        "cover": 37.4,
        "bleaching": 2.4
      },
      {
        "site_no": 20,
        "year": 2023,
        "cover": 36.6,
        "bleaching": 2.5
      },
      {
        "site_no": 20,
        "year": 2024,
        "cover": 36.4,
        "bleaching": 32.7
      },
      {
        "site_no": 21,
        "year": 2020,
        "cover": 25.9,
        "bleaching": 5.9
      },
      {
        "site_no": 21,
        "year": 2021,
        "cover": 32.7,
        "bleaching": 0.2
      },
      {
        "site_no": 21,
        "year": 2022,
        "cover": 27.7,
        "bleaching": 2.2
      },
      {
        "site_no": 21,
        "year": 2023,
        "cover": 31.0,
        "bleaching": 0.3
      },
      {
        "site_no": 21,
        "year": 2024,
        "cover": 30.1,
        "bleaching": 13.1
      },
      {
        "site_no": 22,
        "year": 2020,
        "cover": 21.3,
        "bleaching": 3.7
      },
      {
        "site_no": 22,
        "year": 2021,
        "cover": 22.3,
        "bleaching": 0.5
      },
      {
        "site_no": 22,
        "year": 2022,
        "cover": 25.2,
        "bleaching": 7.4
      },
      {
        "site_no": 22,
        "year": 2023,
        "cover": 21.5,
        "bleaching": 2.0
      },
      {
        "site_no": 22,
        "year": 2024,
        "cover": 21.3,
        "bleaching": 32.5
      },
      {
        "site_no": 23,
        "year": 2020,
        "cover": 19.7,
        "bleaching": 0.4
      },
      {
        "site_no": 23,
        "year": 2021,
        "cover": 17.0,
        "bleaching": 0.9
      },
      {
        "site_no": 23,
        "year": 2022,
        "cover": 11.6,
        "bleaching": 44.7
      },
      {
        "site_no": 23,
        "year": 2023,
        "cover": 18.1,
        "bleaching": 7.2
      },
      {
        "site_no": 23,
        "year": 2024,
        "cover": 17.6,
        "bleaching": 8.9
      },
      {
        "site_no": 24,
        "year": 2020,
        "cover": 27.8,
        "bleaching": 3.3
      },
      {
        "site_no": 24,
        "year": 2021,
        "cover": 30.0,
        "bleaching": 2.7
      },
      {
        "site_no": 24,
        "year": 2022,
        "cover": 28.5,
        "bleaching": 3.0
      },
      {
        "site_no": 24,
        "year": 2023,
        "cover": 27.0,
        "bleaching": 2.8
      },
      {
        "site_no": 24,
        "year": 2024,
        "cover": 27.7,
        "bleaching": 6.3
      },
      {
        "site_no": 25,
        "year": 2024,
        "cover": 15.0,
        "bleaching": 36.1
      },
      {
        "site_no": 26,
        "year": 2021,
        "cover": 16.1,
        "bleaching": 0.0
      },
      {
        "site_no": 26,
        "year": 2022,
        "cover": 16.4,
        "bleaching": 7.9
      }
    ],
    "pearson_r": -0.223,
    "p_value": 0.018,
    "n": 112
  },
  "acropora_selectivity": {
    "data": [
      {
        "site_no": 1,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 1,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 1,
        "year": 2022,
        "bleaching_all": 13.1,
        "bleaching_acropora": 10.8,
        "selectivity": -2.2
      },
      {
        "site_no": 1,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 1,
        "year": 2024,
        "bleaching_all": 56.4,
        "bleaching_acropora": 54.4,
        "selectivity": -1.9
      },
      {
        "site_no": 2,
        "year": 2022,
        "bleaching_all": 43.8,
        "bleaching_acropora": 39.2,
        "selectivity": -4.6
      },
      {
        "site_no": 3,
        "year": 2020,
        "bleaching_all": 8.7,
        "bleaching_acropora": 12.0,
        "selectivity": 3.3
      },
      {
        "site_no": 3,
        "year": 2021,
        "bleaching_all": 5.3,
        "bleaching_acropora": 0.0,
        "selectivity": -5.3
      },
      {
        "site_no": 3,
        "year": 2022,
        "bleaching_all": 41.3,
        "bleaching_acropora": 40.7,
        "selectivity": -0.7
      },
      {
        "site_no": 3,
        "year": 2023,
        "bleaching_all": 1.3,
        "bleaching_acropora": 1.3,
        "selectivity": 0.0
      },
      {
        "site_no": 3,
        "year": 2024,
        "bleaching_all": 62.3,
        "bleaching_acropora": 47.3,
        "selectivity": -15.0
      },
      {
        "site_no": 4,
        "year": 2020,
        "bleaching_all": 2.0,
        "bleaching_acropora": 4.5,
        "selectivity": 2.5
      },
      {
        "site_no": 4,
        "year": 2021,
        "bleaching_all": 0.1,
        "bleaching_acropora": 1.6,
        "selectivity": 1.5
      },
      {
        "site_no": 4,
        "year": 2022,
        "bleaching_all": 5.3,
        "bleaching_acropora": 13.2,
        "selectivity": 7.9
      },
      {
        "site_no": 4,
        "year": 2023,
        "bleaching_all": 0.1,
        "bleaching_acropora": 1.5,
        "selectivity": 1.4
      },
      {
        "site_no": 4,
        "year": 2024,
        "bleaching_all": 57.6,
        "bleaching_acropora": 63.8,
        "selectivity": 6.2
      },
      {
        "site_no": 5,
        "year": 2020,
        "bleaching_all": 2.2,
        "bleaching_acropora": 9.9,
        "selectivity": 7.6
      },
      {
        "site_no": 5,
        "year": 2021,
        "bleaching_all": 0.1,
        "bleaching_acropora": 2.9,
        "selectivity": 2.8
      },
      {
        "site_no": 5,
        "year": 2022,
        "bleaching_all": 3.4,
        "bleaching_acropora": 13.7,
        "selectivity": 10.3
      },
      {
        "site_no": 5,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 1.2,
        "selectivity": 1.2
      },
      {
        "site_no": 5,
        "year": 2024,
        "bleaching_all": 77.8,
        "bleaching_acropora": 85.5,
        "selectivity": 7.8
      },
      {
        "site_no": 6,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 6,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 6,
        "year": 2022,
        "bleaching_all": 0.3,
        "bleaching_acropora": 14.2,
        "selectivity": 13.8
      },
      {
        "site_no": 6,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 6,
        "year": 2024,
        "bleaching_all": 88.6,
        "bleaching_acropora": 88.6,
        "selectivity": 0.0
      },
      {
        "site_no": 7,
        "year": 2020,
        "bleaching_all": 0.6,
        "bleaching_acropora": 0.0,
        "selectivity": -0.6
      },
      {
        "site_no": 7,
        "year": 2021,
        "bleaching_all": 0.2,
        "bleaching_acropora": 0.0,
        "selectivity": -0.2
      },
      {
        "site_no": 7,
        "year": 2022,
        "bleaching_all": 0.4,
        "bleaching_acropora": 0.0,
        "selectivity": -0.4
      },
      {
        "site_no": 7,
        "year": 2023,
        "bleaching_all": 0.2,
        "bleaching_acropora": 0.0,
        "selectivity": -0.2
      },
      {
        "site_no": 7,
        "year": 2024,
        "bleaching_all": 22.9,
        "bleaching_acropora": 42.1,
        "selectivity": 19.2
      },
      {
        "site_no": 8,
        "year": 2022,
        "bleaching_all": 3.8,
        "bleaching_acropora": 3.1,
        "selectivity": -0.6
      },
      {
        "site_no": 9,
        "year": 2020,
        "bleaching_all": 1.8,
        "bleaching_acropora": 3.1,
        "selectivity": 1.2
      },
      {
        "site_no": 9,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 9,
        "year": 2022,
        "bleaching_all": 22.8,
        "bleaching_acropora": 29.5,
        "selectivity": 6.8
      },
      {
        "site_no": 9,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 9,
        "year": 2024,
        "bleaching_all": 51.2,
        "bleaching_acropora": 64.5,
        "selectivity": 13.2
      },
      {
        "site_no": 10,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 10,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 10,
        "year": 2022,
        "bleaching_all": 6.9,
        "bleaching_acropora": 6.9,
        "selectivity": 0.0
      },
      {
        "site_no": 10,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 10,
        "year": 2024,
        "bleaching_all": 67.5,
        "bleaching_acropora": 68.8,
        "selectivity": 1.2
      },
      {
        "site_no": 11,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 11,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 11,
        "year": 2022,
        "bleaching_all": 38.0,
        "bleaching_acropora": 73.3,
        "selectivity": 35.4
      },
      {
        "site_no": 11,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 11,
        "year": 2024,
        "bleaching_all": 7.0,
        "bleaching_acropora": 3.3,
        "selectivity": -3.7
      },
      {
        "site_no": 12,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 12,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 12,
        "year": 2022,
        "bleaching_all": 58.3,
        "bleaching_acropora": 71.7,
        "selectivity": 13.4
      },
      {
        "site_no": 12,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 12,
        "year": 2024,
        "bleaching_all": 4.9,
        "bleaching_acropora": 4.1,
        "selectivity": -0.7
      },
      {
        "site_no": 13,
        "year": 2020,
        "bleaching_all": 28.5,
        "bleaching_acropora": 25.6,
        "selectivity": -2.9
      },
      {
        "site_no": 13,
        "year": 2021,
        "bleaching_all": 47.0,
        "bleaching_acropora": 44.8,
        "selectivity": -2.2
      },
      {
        "site_no": 13,
        "year": 2022,
        "bleaching_all": 86.8,
        "bleaching_acropora": 86.8,
        "selectivity": -0.0
      },
      {
        "site_no": 13,
        "year": 2023,
        "bleaching_all": 30.7,
        "bleaching_acropora": 30.1,
        "selectivity": -0.6
      },
      {
        "site_no": 13,
        "year": 2024,
        "bleaching_all": 82.9,
        "bleaching_acropora": 83.9,
        "selectivity": 1.0
      },
      {
        "site_no": 14,
        "year": 2020,
        "bleaching_all": 59.1,
        "bleaching_acropora": 53.7,
        "selectivity": -5.5
      },
      {
        "site_no": 14,
        "year": 2021,
        "bleaching_all": 58.9,
        "bleaching_acropora": 52.8,
        "selectivity": -6.1
      },
      {
        "site_no": 14,
        "year": 2022,
        "bleaching_all": 89.5,
        "bleaching_acropora": 92.6,
        "selectivity": 3.0
      },
      {
        "site_no": 14,
        "year": 2023,
        "bleaching_all": 48.6,
        "bleaching_acropora": 44.9,
        "selectivity": -3.7
      },
      {
        "site_no": 14,
        "year": 2024,
        "bleaching_all": 94.5,
        "bleaching_acropora": 95.1,
        "selectivity": 0.6
      },
      {
        "site_no": 15,
        "year": 2020,
        "bleaching_all": 57.6,
        "bleaching_acropora": 50.7,
        "selectivity": -6.9
      },
      {
        "site_no": 15,
        "year": 2021,
        "bleaching_all": 66.0,
        "bleaching_acropora": 64.6,
        "selectivity": -1.4
      },
      {
        "site_no": 15,
        "year": 2022,
        "bleaching_all": 87.1,
        "bleaching_acropora": 87.5,
        "selectivity": 0.4
      },
      {
        "site_no": 15,
        "year": 2023,
        "bleaching_all": 50.5,
        "bleaching_acropora": 44.9,
        "selectivity": -5.7
      },
      {
        "site_no": 15,
        "year": 2024,
        "bleaching_all": 85.5,
        "bleaching_acropora": 87.9,
        "selectivity": 2.4
      },
      {
        "site_no": 16,
        "year": 2020,
        "bleaching_all": 69.5,
        "bleaching_acropora": 67.6,
        "selectivity": -1.9
      },
      {
        "site_no": 16,
        "year": 2021,
        "bleaching_all": 69.2,
        "bleaching_acropora": 67.7,
        "selectivity": -1.6
      },
      {
        "site_no": 16,
        "year": 2022,
        "bleaching_all": 90.8,
        "bleaching_acropora": 94.5,
        "selectivity": 3.7
      },
      {
        "site_no": 16,
        "year": 2023,
        "bleaching_all": 46.6,
        "bleaching_acropora": 38.4,
        "selectivity": -8.2
      },
      {
        "site_no": 16,
        "year": 2024,
        "bleaching_all": 94.1,
        "bleaching_acropora": 97.6,
        "selectivity": 3.5
      },
      {
        "site_no": 17,
        "year": 2020,
        "bleaching_all": 46.9,
        "bleaching_acropora": 42.9,
        "selectivity": -4.0
      },
      {
        "site_no": 17,
        "year": 2021,
        "bleaching_all": 44.7,
        "bleaching_acropora": 44.5,
        "selectivity": -0.2
      },
      {
        "site_no": 17,
        "year": 2022,
        "bleaching_all": 92.9,
        "bleaching_acropora": 76.8,
        "selectivity": -16.1
      },
      {
        "site_no": 17,
        "year": 2023,
        "bleaching_all": 35.7,
        "bleaching_acropora": 35.2,
        "selectivity": -0.5
      },
      {
        "site_no": 17,
        "year": 2024,
        "bleaching_all": 88.3,
        "bleaching_acropora": 92.3,
        "selectivity": 4.0
      },
      {
        "site_no": 18,
        "year": 2020,
        "bleaching_all": 14.2,
        "bleaching_acropora": 23.0,
        "selectivity": 8.7
      },
      {
        "site_no": 18,
        "year": 2021,
        "bleaching_all": 0.7,
        "bleaching_acropora": 0.4,
        "selectivity": -0.3
      },
      {
        "site_no": 18,
        "year": 2022,
        "bleaching_all": 0.5,
        "bleaching_acropora": 0.2,
        "selectivity": -0.2
      },
      {
        "site_no": 18,
        "year": 2023,
        "bleaching_all": 0.6,
        "bleaching_acropora": 0.5,
        "selectivity": -0.1
      },
      {
        "site_no": 18,
        "year": 2024,
        "bleaching_all": 0.5,
        "bleaching_acropora": 0.2,
        "selectivity": -0.2
      },
      {
        "site_no": 19,
        "year": 2020,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 19,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 19,
        "year": 2022,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 19,
        "year": 2023,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 19,
        "year": 2024,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 20,
        "year": 2022,
        "bleaching_all": 2.4,
        "bleaching_acropora": 0.6,
        "selectivity": -1.8
      },
      {
        "site_no": 20,
        "year": 2023,
        "bleaching_all": 2.5,
        "bleaching_acropora": 0.6,
        "selectivity": -1.8
      },
      {
        "site_no": 20,
        "year": 2024,
        "bleaching_all": 32.7,
        "bleaching_acropora": 30.5,
        "selectivity": -2.1
      },
      {
        "site_no": 21,
        "year": 2020,
        "bleaching_all": 5.9,
        "bleaching_acropora": 8.9,
        "selectivity": 3.0
      },
      {
        "site_no": 21,
        "year": 2021,
        "bleaching_all": 0.2,
        "bleaching_acropora": 0.2,
        "selectivity": 0.0
      },
      {
        "site_no": 21,
        "year": 2022,
        "bleaching_all": 2.2,
        "bleaching_acropora": 9.2,
        "selectivity": 7.0
      },
      {
        "site_no": 21,
        "year": 2023,
        "bleaching_all": 0.3,
        "bleaching_acropora": 0.4,
        "selectivity": 0.1
      },
      {
        "site_no": 21,
        "year": 2024,
        "bleaching_all": 13.1,
        "bleaching_acropora": 8.9,
        "selectivity": -4.3
      },
      {
        "site_no": 22,
        "year": 2020,
        "bleaching_all": 3.7,
        "bleaching_acropora": 2.7,
        "selectivity": -1.0
      },
      {
        "site_no": 22,
        "year": 2021,
        "bleaching_all": 0.5,
        "bleaching_acropora": 0.3,
        "selectivity": -0.2
      },
      {
        "site_no": 22,
        "year": 2022,
        "bleaching_all": 7.4,
        "bleaching_acropora": 6.7,
        "selectivity": -0.7
      },
      {
        "site_no": 22,
        "year": 2023,
        "bleaching_all": 2.0,
        "bleaching_acropora": 0.6,
        "selectivity": -1.4
      },
      {
        "site_no": 22,
        "year": 2024,
        "bleaching_all": 32.5,
        "bleaching_acropora": 32.0,
        "selectivity": -0.5
      },
      {
        "site_no": 23,
        "year": 2020,
        "bleaching_all": 0.4,
        "bleaching_acropora": 0.0,
        "selectivity": -0.4
      },
      {
        "site_no": 23,
        "year": 2021,
        "bleaching_all": 0.9,
        "bleaching_acropora": 0.0,
        "selectivity": -0.9
      },
      {
        "site_no": 23,
        "year": 2022,
        "bleaching_all": 44.7,
        "bleaching_acropora": 43.1,
        "selectivity": -1.6
      },
      {
        "site_no": 23,
        "year": 2023,
        "bleaching_all": 7.2,
        "bleaching_acropora": 6.2,
        "selectivity": -0.9
      },
      {
        "site_no": 23,
        "year": 2024,
        "bleaching_all": 8.9,
        "bleaching_acropora": 11.1,
        "selectivity": 2.2
      },
      {
        "site_no": 24,
        "year": 2020,
        "bleaching_all": 3.3,
        "bleaching_acropora": 3.3,
        "selectivity": 0.0
      },
      {
        "site_no": 24,
        "year": 2021,
        "bleaching_all": 2.7,
        "bleaching_acropora": 2.7,
        "selectivity": 0.0
      },
      {
        "site_no": 24,
        "year": 2022,
        "bleaching_all": 3.0,
        "bleaching_acropora": 2.0,
        "selectivity": -1.0
      },
      {
        "site_no": 24,
        "year": 2023,
        "bleaching_all": 2.8,
        "bleaching_acropora": 2.8,
        "selectivity": 0.0
      },
      {
        "site_no": 24,
        "year": 2024,
        "bleaching_all": 6.3,
        "bleaching_acropora": 7.7,
        "selectivity": 1.3
      },
      {
        "site_no": 25,
        "year": 2024,
        "bleaching_all": 36.1,
        "bleaching_acropora": 54.3,
        "selectivity": 18.2
      },
      {
        "site_no": 26,
        "year": 2021,
        "bleaching_all": 0.0,
        "bleaching_acropora": 0.0,
        "selectivity": 0.0
      },
      {
        "site_no": 26,
        "year": 2022,
        "bleaching_all": 7.9,
        "bleaching_acropora": 1.3,
        "selectivity": -6.6
      }
    ],
    "mean_selectivity": 0.8,
    "n": 113
  }
};
